### ISSUE TITLE
Handle YouTube video comments being disabled

### ISSUE THREAD

**Issue by phazonoverload** [orbit-love/community-js-youtube-orbit#3]
Probably falls into the general bucket of error handling that @phazonoverload mentions (but let me know if you'd rather I raised this as a separate issue). We hit an error because we have comments turned off on (at least one) video. I'm not sure whether this stopped the process of gathering any comments at all?

```
Run npx @orbit-love/youtube --comments --hours=24
npx: installed 24 in 3.031s
(node:1494) UnhandledPromiseRejectionWarning: Error: Error: The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.
    at /home/runner/.npm/_npx/1494/lib/node_modules/@orbit-love/youtube/src/comments.js:22:67
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /home/runner/.npm/_npx/1494/lib/node_modules/@orbit-love/youtube/src/comments.js:21:34
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
(node:1494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

_Originally posted by @lizrice in https://github.com/orbit-love/community-js-youtube-orbit/issues/2#issuecomment-859445491_

**Comment by phazonoverload** [comment]
@lizrice as you can tell this is unexpected behavior. As part of my research I will be able to tell you if this blocked comment activity creations. My hunch is that it did - as this integration gets all comments before adding any, and this failure is in the first step. I’ll keep you in the loop

**Comment by phazonoverload** [comment]
This is now fixed 😄 If you experience any other unexpected behaviour just let us know ,and thanks for the report ✨
